// @ts-nocheck
"use server";

import { revalidatePath } from "next/cache";

import { createSupabaseServerClient } from "@/lib/supabase/server";
import type { Database } from "@/types";

type AttendanceStatus = Database["public"]["Tables"]["attendances"]["Row"]["status"];
type NotificationType = Database["public"]["Tables"]["notifications"]["Row"]["type"];
type EventRecord = Pick<Database["public"]["Tables"]["events"]["Row"], "id" | "group_id" | "organizer_id" | "event_date" | "location" | "description" | "status" | "updated_at">;
type RotationLookup = Pick<Database["public"]["Tables"]["rotation"]["Row"], "group_id" | "user_id" | "month" | "is_current">;
type AttendanceLookup = Pick<Database["public"]["Tables"]["attendances"]["Row"], "event_id" | "member_id" | "status" | "updated_at">;
type MemberLookup = Pick<Database["public"]["Tables"]["members"]["Row"], "user_id">;
type NotificationInsert = Database["public"]["Tables"]["notifications"]["Insert"];

interface QuerySingle<T> { maybeSingle(): Promise<{ data: T | null; error: { message: string } | null }>; single(): Promise<{ data: T; error: { message: string } | null }>; }
interface QueryMany<T> { then: Promise<{ data: T[]; error: { message: string } | null }>['then']; }
interface EventsTable {
  select(columns: string): {
    eq(column: string, value: string): QuerySingle<EventRecord> & { neq(column: string, value: string): { gte(column: string, value: string): { lt(column: string, value: string): { order(column: string, options: { ascending: boolean }): QuerySingle<EventRecord>; }; }; }; }; in(column: string, values: string[]): { gte(column: string, value: string): { lt(column: string, value: string): { order(column: string, options: { ascending: boolean }): { limit(count: number): QuerySingle<EventRecord>; }; }; }; };
  };
  insert(values: Database["public"]["Tables"]["events"]["Insert"]): { select(columns: string): { single(): Promise<{ data: EventRecord; error: { message: string } | null }>; }; };
  update(values: Database["public"]["Tables"]["events"]["Update"]): { eq(column: string, value: string): Promise<{ error: { message: string } | null }> } & { eq(column: string, value: string): { select(columns: string): { single(): Promise<{ data: EventRecord; error: { message: string } | null }> } } };
}
interface RotationTable { select(columns: string): { eq(column: string, value: string | boolean): { eq(column: string, value: string | boolean): QuerySingle<RotationLookup> } } }
interface MembersTable { select(columns: string): { eq(column: string, value: string): Promise<{ data: MemberLookup[]; error: { message: string } | null }> & { order(column: string, options: { ascending: boolean }): { limit(count: number): QuerySingle<{ group_id: string }> } } } }
interface AttendancesTable { select(columns: string): { eq(column: string, value: string): Promise<{ data: Array<{ status: AttendanceStatus }>; error: { message: string } | null }> & { eq(column: string, value: string): QuerySingle<{ status: AttendanceStatus }> } }; upsert(values: Database["public"]["Tables"]["attendances"]["Insert"], options: { onConflict: string }): { select(columns: string): { single(): Promise<{ data: AttendanceLookup; error: { message: string } | null }> } } }
interface NotificationsTable { insert(values: NotificationInsert[]): Promise<{ error: { message: string } | null }> }

export type ActionErrorCode = "unauthorized" | "forbidden" | "missing_date" | "event_exists" | "not_found" | "invalid_status" | "invalid_event_status" | "database_error";
export type ActionError = { code: ActionErrorCode; message: string };
export type ActionResult<T> = { success: true; data: T } | { success: false; error: ActionError };
export type EventPayload = { date: string; location: string; description: string };
export type AttendanceSummary = { va: number; no_va: number; tal_vez: number; sin_respuesta: number; total: number };

function trimOptional(value: string): string | null { const trimmed = value.trim(); return trimmed.length > 0 ? trimmed : null; }
function normalizePayload(payload: EventPayload): ActionResult<{ eventDate: string; location: string | null; description: string | null }> {
  if (!payload.date.trim()) return { success: false, error: { code: "missing_date", message: "La fecha es obligatoria para crear el evento" } };
  const description = payload.description.trim();
  if (description.length > 500) return { success: false, error: { code: "database_error", message: "La descripción no puede superar los 500 caracteres" } };
  return { success: true, data: { eventDate: payload.date, location: trimOptional(payload.location), description: description || null } };
}
function monthRange(date: string) { const [year, month] = date.split("-").map(Number); return { start: new Date(Date.UTC(year, month - 1, 1)).toISOString().slice(0, 10), end: new Date(Date.UTC(year, month, 1)).toISOString().slice(0, 10) }; }
async function getCurrentUserId(): Promise<ActionResult<string>> { const supabase = createSupabaseServerClient(); const { data, error } = await supabase.auth.getUser(); if (error || !data.user) return { success: false, error: { code: "unauthorized", message: "Debes iniciar sesión para continuar" } }; return { success: true, data: data.user.id }; }
async function getCurrentRotation(userId: string): Promise<ActionResult<RotationLookup>> { const rotationTable = createSupabaseServerClient().from("rotation") as unknown as RotationTable; const { data, error } = await rotationTable.select("group_id, user_id, month, is_current").eq("user_id", userId).eq("is_current", true).maybeSingle(); if (error) return { success: false, error: { code: "database_error", message: error.message } }; if (!data) return { success: false, error: { code: "forbidden", message: "Solo el organizador del mes puede crear el evento" } }; return { success: true, data }; }
async function getEventById(eventId: string): Promise<ActionResult<EventRecord>> { const eventsTable = createSupabaseServerClient().from("events") as unknown as EventsTable; const { data, error } = await eventsTable.select("id, group_id, organizer_id, event_date, location, description, status, updated_at").eq("id", eventId).maybeSingle(); if (error) return { success: false, error: { code: "database_error", message: error.message } }; if (!data) return { success: false, error: { code: "not_found", message: "No encontramos el evento solicitado" } }; return { success: true, data }; }
async function insertNotifications(groupId: string, eventId: string, type: NotificationType): Promise<number> { const supabase = createSupabaseServerClient(); const membersTable = supabase.from("members") as unknown as MembersTable; const notificationsTable = supabase.from("notifications") as unknown as NotificationsTable; const { data: members, error: membersError } = await membersTable.select("user_id").eq("group_id", groupId); if (membersError || !members) { console.error("notifications.members_error", membersError?.message ?? "missing members"); return 0; } const rows: NotificationInsert[] = members.map((member) => ({ group_id: groupId, event_id: eventId, user_id: member.user_id, type, is_read: false })); if (rows.length === 0) return 0; const { error } = await notificationsTable.insert(rows); if (error) { console.error("notifications.insert_error", error.message); return 0; } return rows.length; }

export async function createEvent(payload: EventPayload): Promise<ActionResult<EventRecord>> { const auth = await getCurrentUserId(); if (!auth.success) return auth; const normalized = normalizePayload(payload); if (!normalized.success) return normalized; const rotation = await getCurrentRotation(auth.data); if (!rotation.success) return rotation; const eventsTable = createSupabaseServerClient().from("events") as unknown as EventsTable; const { start, end } = monthRange(normalized.data.eventDate); const { data: existingEvent, error: existingEventError } = await eventsTable.select("id, group_id, organizer_id, event_date, location, description, status, updated_at").eq("group_id", rotation.data.group_id).neq("status", "closed").gte("event_date", start).lt("event_date", end).order("event_date", { ascending: true }).maybeSingle(); if (existingEventError) return { success: false, error: { code: "database_error", message: existingEventError.message } }; if (existingEvent) return { success: false, error: { code: "event_exists", message: "Ya hay un evento activo este mes" } }; const { data, error } = await eventsTable.insert({ group_id: rotation.data.group_id, organizer_id: auth.data, event_date: normalized.data.eventDate, location: normalized.data.location, description: normalized.data.description, status: "draft" }).select("id, group_id, organizer_id, event_date, location, description, status, updated_at").single(); if (error) return { success: false, error: { code: error.message.toLowerCase().includes("unique") ? "event_exists" : "database_error", message: error.message.toLowerCase().includes("unique") ? "Ya hay un evento activo este mes" : error.message } }; revalidatePath("/dashboard"); return { success: true, data }; }
export async function updateEvent(eventId: string, payload: EventPayload): Promise<ActionResult<EventRecord>> { const auth = await getCurrentUserId(); if (!auth.success) return auth; const normalized = normalizePayload(payload); if (!normalized.success) return normalized; const eventLookup = await getEventById(eventId); if (!eventLookup.success) return eventLookup; if (eventLookup.data.organizer_id != auth.data) return { success: false, error: { code: "forbidden", message: "Solo la persona organizadora puede editar el evento" } }; const eventsTable = createSupabaseServerClient().from("events") as unknown as EventsTable; const { data, error } = await eventsTable.update({ event_date: normalized.data.eventDate, location: normalized.data.location, description: normalized.data.description, updated_at: new Date().toISOString() }).eq("id", eventId).select("id, group_id, organizer_id, event_date, location, description, status, updated_at").single(); if (error) return { success: false, error: { code: "database_error", message: error.message } }; revalidatePath("/dashboard"); revalidatePath(`/dashboard/events/${eventId}`); return { success: true, data }; }
export async function publishEvent(eventId: string): Promise<ActionResult<{ eventId: string; notifiedMembers: number }>> { const auth = await getCurrentUserId(); if (!auth.success) return auth; const eventLookup = await getEventById(eventId); if (!eventLookup.success) return eventLookup; if (eventLookup.data.organizer_id !== auth.data) return { success: false, error: { code: "forbidden", message: "Solo la persona organizadora puede notificar al grupo" } }; if (eventLookup.data.status !== "draft") return { success: false, error: { code: "invalid_event_status", message: "Solo puedes publicar eventos en borrador" } }; const eventsTable = createSupabaseServerClient().from("events") as unknown as EventsTable; const { error } = await eventsTable.update({ status: "published", updated_at: new Date().toISOString() }).eq("id", eventId); if (error) return { success: false, error: { code: "database_error", message: error.message } }; const notifiedMembers = await insertNotifications(eventLookup.data.group_id, eventId, "event_published"); revalidatePath("/dashboard"); return { success: true, data: { eventId, notifiedMembers } }; }
export async function notifyGroupOfUpdate(eventId: string): Promise<ActionResult<{ eventId: string; notifiedMembers: number }>> { const auth = await getCurrentUserId(); if (!auth.success) return auth; const eventLookup = await getEventById(eventId); if (!eventLookup.success) return eventLookup; if (eventLookup.data.organizer_id !== auth.data) return { success: false, error: { code: "forbidden", message: "Solo la persona organizadora puede reenviar actualizaciones" } }; const notifiedMembers = await insertNotifications(eventLookup.data.group_id, eventId, "event_updated"); revalidatePath("/dashboard"); return { success: true, data: { eventId, notifiedMembers } }; }
export async function updateAttendance(eventId: string, status: AttendanceStatus): Promise<ActionResult<AttendanceLookup>> { const auth = await getCurrentUserId(); if (!auth.success) return auth; if (!["va", "no_va", "tal_vez"].includes(status)) return { success: false, error: { code: "invalid_status", message: "El estado de asistencia no es válido" } }; const eventLookup = await getEventById(eventId); if (!eventLookup.success) return eventLookup as unknown as ActionResult<AttendanceLookup>; if (eventLookup.data.status !== "published") return { success: false, error: { code: "invalid_event_status", message: "Solo puedes responder a eventos convocados" } }; const attendancesTable = createSupabaseServerClient().from("attendances") as unknown as AttendancesTable; const { data, error } = await attendancesTable.upsert({ event_id: eventId, member_id: auth.data, status, updated_at: new Date().toISOString() }, { onConflict: "event_id,member_id" }).select("event_id, member_id, status, updated_at").single(); if (error) return { success: false, error: { code: "database_error", message: error.message } }; revalidatePath("/dashboard"); return { success: true, data }; }
export async function getAttendanceSummary(eventId: string): Promise<ActionResult<AttendanceSummary>> { const eventLookup = await getEventById(eventId); if (!eventLookup.success) return eventLookup as unknown as ActionResult<AttendanceSummary>; const supabase = createSupabaseServerClient(); const attendancesTable = supabase.from("attendances") as unknown as AttendancesTable; const membersTable = supabase.from("members") as unknown as MembersTable; const [attendancesResult, membersResult] = await Promise.all([attendancesTable.select("status").eq("event_id", eventId), membersTable.select("user_id").eq("group_id", eventLookup.data.group_id)]); if (attendancesResult.error) return { success: false, error: { code: "database_error", message: attendancesResult.error.message } }; if (membersResult.error) return { success: false, error: { code: "database_error", message: membersResult.error.message } }; const summary: AttendanceSummary = { va: 0, no_va: 0, tal_vez: 0, sin_respuesta: 0, total: membersResult.data.length }; for (const row of attendancesResult.data) { if (row.status === "va") summary.va += 1; if (row.status === "no_va") summary.no_va += 1; if (row.status === "tal_vez") summary.tal_vez += 1; } summary.sin_respuesta = Math.max(summary.total - (summary.va + summary.no_va + summary.tal_vez), 0); return { success: true, data: summary }; }
